// ============================================================
// CARVIBES — CAR DATABASE
// A structured, scalable vehicle database.
//
// Every entry uses REAL vehicle names and specifications.
// Where a specification is not confidently known, it is "N/A"
// (never invented). The array is append-only friendly and is
// designed to scale toward 500+ vehicles. Add new cars by
// pushing a new Car object below.
// ============================================================

export type Category =
  | "supercar"
  | "sports"
  | "luxury"
  | "suv"
  | "electric"
  | "jdm"
  | "classic"
  | "offroad"
  | "daily";

export type Fuel = "Petrol" | "Diesel" | "Hybrid" | "Electric";
export type Transmission = "Automatic" | "Manual" | "Dual-clutch" | "CVT";
export type Drivetrain = "RWD" | "FWD" | "AWD" | "4WD";

export interface Car {
  id: string;
  brand: string;
  model: string;
  generation?: string;
  year: number;
  categories: Category[];
  body: string; // body type
  price: number; // USD, approximate MSRP at time of writing
  engine: string;
  fuel: Fuel;
  hp: number; // horsepower — "0" renders as N/A
  torque?: number; // Nm
  transmission: Transmission;
  drivetrain?: Drivetrain;
  zeroToHundred: number; // seconds — "0" renders as N/A
  topSpeed?: number; // km/h
  weight?: number; // kg
  image: string;
  gallery?: string[];
  tagline?: string;
  overview?: string;
}

// --- Helper to build a realistic Pexels URL with correct dimensions ---
export const px = (id: number, w = 1200, h = 800) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

// ============================================================
// THE DATABASE (curated seed — scales toward 500+)
// ============================================================
export const curatedCars: Car[] = [
  // ---- SUPERCARS / HYPERCARS ----
  {
    id: "ferrari-812-superfast",
    brand: "Ferrari",
    model: "812 Superfast",
    generation: "F152M",
    year: 2021,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 340000,
    engine: "6.5L NA V12",
    fuel: "Petrol",
    hp: 800,
    torque: 718,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 2.9,
    topSpeed: 340,
    weight: 1630,
    image: px(12506011, 1400, 900),
    gallery: [px(12506011, 1400, 900), px(28680795, 1200, 800), px(11931440, 1200, 800)],
    tagline: "The last of the great naturally aspirated V12s.",
    overview:
      "Ferrari's front-engined V12 flagship, the 812 Superfast, channels 800 hp through the rear wheels with an 8,900 rpm redline — a tribute to the marque's most iconic powertrains.",
  },
  {
    id: "lamborghini-huracan-evo",
    brand: "Lamborghini",
    model: "Huracán EVO",
    generation: "LP640-4",
    year: 2021,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 262000,
    engine: "5.2L NA V10",
    fuel: "Petrol",
    hp: 640,
    torque: 600,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 2.9,
    topSpeed: 325,
    weight: 1422,
    image: px(17632113, 1400, 900),
    gallery: [px(17632113, 1400, 900), px(6891807, 1200, 800), px(30687976, 1200, 800)],
    tagline: "A naturally aspirated V10 that screams to 8,500 rpm.",
    overview:
      "The Huracán EVO refines Lamborghini's V10 masterpiece with rear-wheel steering and predictive aerodynamics, wrapping razor-sharp handling in unmistakable Sant'Agata style.",
  },
  {
    id: "bugatti-chiron-super-sport",
    brand: "Bugatti",
    model: "Chiron Super Sport",
    generation: "Type 300",
    year: 2022,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 3900000,
    engine: "8.0L Quad-Turbo W16",
    fuel: "Petrol",
    hp: 1600,
    torque: 1600,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 2.4,
    topSpeed: 440,
    weight: 1995,
    image: px(32364051, 1400, 900),
    gallery: [px(32364051, 1400, 900), px(31417515, 1200, 800)],
    tagline: "1,600 hp. One of the fastest road cars ever built.",
    overview:
      "The Chiron Super Sport elevates Bugatti's quad-turbo W16 to 1,600 hp, blending continent-crossing luxury with performance that once seemed reserved for racing prototypes.",
  },
  {
    id: "mclaren-720s",
    brand: "McLaren",
    model: "720S",
    generation: "Mk1",
    year: 2020,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 300000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 720,
    torque: 770,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 2.9,
    topSpeed: 341,
    weight: 1419,
    image: px(29115178, 1400, 900),
    gallery: [px(29115178, 1400, 900), px(19382415, 1200, 800)],
    tagline: "A lightweight carbon core with supercar speed.",
    overview:
      "Built around a carbon-fibre Monocage, the McLaren 720S pairs a 720 hp twin-turbo V8 with a featherweight structure for breathtaking pace and everyday usability.",
  },
  {
    id: "maserati-mc20",
    brand: "Maserati",
    model: "MC20",
    generation: "M240",
    year: 2022,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 216000,
    engine: "3.0L Twin-Turbo V6",
    fuel: "Petrol",
    hp: 630,
    torque: 730,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 2.9,
    topSpeed: 325,
    weight: 1500,
    image: px(19382415, 1400, 900),
    gallery: [px(19382415, 1400, 900), px(9411653, 1200, 800)],
    tagline: "Maserati's return to the supercar stage.",
    overview:
      "The MC20 marks Maserati's triumphant return with a bespoke Nettuno V6 featuring Formula 1-derived pre-chamber combustion, delivering 630 hp and razor-edge dynamics.",
  },
  {
    id: "koenigsegg-jesko",
    brand: "Koenigsegg",
    model: "Jesko",
    generation: "Agera successor",
    year: 2021,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 3000000,
    engine: "5.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 1600,
    torque: 1500,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 2.5,
    topSpeed: 482,
    weight: 1320,
    image: px(18366087, 1400, 900),
    gallery: [px(18366087, 1400, 900)],
    tagline: "A 1,600 hp missile honed for the track.",
    overview:
      "The Koenigsegg Jesko uses a 5.0L twin-turbo V8 running on E85 to produce up to 1,600 hp, paired with a revolutionary nine-speed multi-clutch 'Light Speed' transmission.",
  },
  {
    id: "pagani-huayra",
    brand: "Pagani",
    model: "Huayra",
    generation: "C9",
    year: 2018,
    categories: ["supercar", "luxury"],
    body: "Coupe",
    price: 2800000,
    engine: "6.0L Twin-Turbo V12",
    fuel: "Petrol",
    hp: 730,
    torque: 1000,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 3.2,
    topSpeed: 370,
    weight: 1350,
    image: px(31417515, 1400, 900),
    gallery: [px(31417515, 1400, 900)],
    tagline: "Automotive art, hand-built in carbon and titanium.",
    overview:
      "A rolling masterpiece from Horacio Pagani, the Huayra blends an AMG-sourced twin-turbo V12 with obsessive craftsmanship and active aerodynamics for an unmatched driving event.",
  },
  {
    id: "rimac-nevera",
    brand: "Rimac",
    model: "Nevera",
    generation: "C_Two",
    year: 2023,
    categories: ["supercar", "electric"],
    body: "Coupe",
    price: 2200000,
    engine: "Quad Electric Motor",
    fuel: "Electric",
    hp: 1914,
    torque: 2360,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 1.85,
    topSpeed: 412,
    weight: 2300,
    image: px(30306584, 1400, 900),
    gallery: [px(30306584, 1400, 900), px(35736779, 1200, 800)],
    tagline: "1,914 electric horsepower. A new era of hypercars.",
    overview:
      "Croatia's Rimac Nevera redefines performance with four electric motors generating 1,914 hp, achieving 0–100 km/h in under two seconds while remaining a usable grand tourer.",
  },
  {
    id: "aston-martin-vantage",
    brand: "Aston Martin",
    model: "Vantage",
    generation: "VH412",
    year: 2021,
    categories: ["sports", "luxury"],
    body: "Coupe",
    price: 146000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 503,
    torque: 685,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 3.6,
    topSpeed: 314,
    weight: 1530,
    image: px(94272, 1400, 900),
    gallery: [px(94272, 1400, 900)],
    tagline: "British elegance with a twin-turbo heart.",
    overview:
      "The Aston Martin Vantage channels a Mercedes-AMG twin-turbo V8 through a beautifully balanced chassis, wrapping raw pace in hand-trimmed British luxury.",
  },
  {
    id: "mercedes-amg-gt-r",
    brand: "Mercedes-AMG",
    model: "GT R",
    generation: "C190",
    year: 2019,
    categories: ["sports", "supercar"],
    body: "Coupe",
    price: 163000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 577,
    torque: 700,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 3.6,
    topSpeed: 318,
    weight: 1554,
    image: px(16511358, 1400, 900),
    gallery: [px(16511358, 1400, 900), px(7662147, 1200, 800), px(16124126, 1200, 800)],
    tagline: "The 'Beast of the Green Hell'.",
    overview:
      "Developed on the Nürburgring — hence its 'Green Hell Magno' paint — the Mercedes-AMG GT R is a focused, rear-wheel-drive track weapon with active aero and rear steering.",
  },
  {
    id: "porsche-911-gt3",
    brand: "Porsche",
    model: "911 GT3",
    generation: "992",
    year: 2022,
    categories: ["sports", "supercar"],
    body: "Coupe",
    price: 162000,
    engine: "4.0L NA Flat-6",
    fuel: "Petrol",
    hp: 510,
    torque: 470,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 3.4,
    topSpeed: 318,
    weight: 1435,
    image: px(38234790, 1400, 900),
    gallery: [px(38234790, 1400, 900), px(35849576, 1200, 800)],
    tagline: "The purist's 911 — a 9,000 rpm flat-six.",
    overview:
      "Porsche's 911 GT3 carries a naturally aspirated 4.0L flat-six spinning to 9,000 rpm, double-wishbone front suspension and motorsport DNA throughout — the benchmark driver's car.",
  },
  {
    id: "porsche-911-turbo-s",
    brand: "Porsche",
    model: "911 Turbo S",
    generation: "992",
    year: 2021,
    categories: ["sports", "supercar"],
    body: "Coupe",
    price: 207000,
    engine: "3.8L Twin-Turbo Flat-6",
    fuel: "Petrol",
    hp: 650,
    torque: 800,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 2.7,
    topSpeed: 330,
    weight: 1640,
    image: px(35849576, 1400, 900),
    gallery: [px(35849576, 1400, 900), px(35831596, 1200, 800)],
    tagline: "Everyday usability, supercar acceleration.",
    overview:
      "The 911 Turbo S delivers 650 hp with astonishing 2.7-second acceleration to 100 km/h, yet remains one of the most usable all-weather supercars ever produced.",
  },
  {
    id: "nissan-gtr-nismo",
    brand: "Nissan",
    model: "GT-R Nismo",
    generation: "R35",
    year: 2021,
    categories: ["jdm", "sports", "supercar"],
    body: "Coupe",
    price: 210000,
    engine: "3.8L Twin-Turbo V6",
    fuel: "Petrol",
    hp: 600,
    torque: 652,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 2.9,
    topSpeed: 315,
    weight: 1730,
    image: px(20131555, 1400, 900),
    gallery: [px(20131555, 1400, 900), px(19557554, 1200, 800), px(20131557, 1200, 800)],
    tagline: "Godzilla — the hand-built icon.",
    overview:
      "Each hand-assembled VR38DETT twin-turbo V6 powers the GT-R Nismo to 600 hp, with ATTESA all-wheel drive delivering brutal, relentless pace — the legendary 'Godzilla'.",
  },
  {
    id: "nissan-skyline-r34",
    brand: "Nissan",
    model: "Skyline GT-R R34",
    generation: "R34",
    year: 2002,
    categories: ["jdm", "classic", "sports"],
    body: "Coupe",
    price: 180000,
    engine: "2.6L Twin-Turbo I6",
    fuel: "Petrol",
    hp: 280,
    torque: 392,
    transmission: "Manual",
    drivetrain: "AWD",
    zeroToHundred: 5.2,
    topSpeed: 250,
    weight: 1560,
    image: px(19557554, 1400, 900),
    gallery: [px(19557554, 1400, 900), px(20131557, 1200, 800)],
    tagline: "The JDM legend immortalized on screen.",
    overview:
      "The R34 Skyline GT-R remains one of the most revered JDM icons, powered by the RB26DETT twin-turbo straight-six and immortalized in motorsport and popular culture alike.",
  },
  {
    id: "toyota-supra-mk4",
    brand: "Toyota",
    model: "Supra A80",
    generation: "MK4 (A80)",
    year: 1998,
    categories: ["jdm", "classic", "sports"],
    body: "Coupe",
    price: 120000,
    engine: "3.0L Twin-Turbo I6",
    fuel: "Petrol",
    hp: 276,
    torque: 431,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 4.9,
    topSpeed: 250,
    weight: 1490,
    image: px(15513894, 1400, 900),
    gallery: [px(15513894, 1400, 900), px(13627441, 1200, 800), px(37301057, 1200, 800)],
    tagline: "The turbocharged hero of a generation.",
    overview:
      "The fourth-generation Supra's legendary 2JZ-GTE straight-six made it a tuning and motorsport phenomenon, cementing its status as one of the greatest JDM cars of all time.",
  },
  {
    id: "toyota-supra-a90",
    brand: "Toyota",
    model: "GR Supra",
    generation: "A90",
    year: 2023,
    categories: ["sports", "jdm"],
    body: "Coupe",
    price: 56000,
    engine: "3.0L Turbo I6",
    fuel: "Petrol",
    hp: 382,
    torque: 500,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 4.1,
    topSpeed: 250,
    weight: 1540,
    image: px(13627441, 1400, 900),
    gallery: [px(13627441, 1400, 900), px(37301057, 1200, 800)],
    tagline: "The return of the Supra name.",
    overview:
      "Revived in collaboration with BMW, the A90 GR Supra pairs a turbocharged BMW straight-six with Toyota's chassis tuning for a sharp, playful modern sports car.",
  },
  {
    id: "audi-r8-v10",
    brand: "Audi",
    model: "R8 V10",
    generation: "Type 4S",
    year: 2022,
    categories: ["supercar", "sports"],
    body: "Coupe",
    price: 180000,
    engine: "5.2L NA V10",
    fuel: "Petrol",
    hp: 610,
    torque: 560,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 3.1,
    topSpeed: 331,
    weight: 1595,
    image: px(30687976, 1400, 900),
    gallery: [px(30687976, 1400, 900)],
    tagline: "A Lamborghini V10 in German clothing.",
    overview:
      "Sharing its naturally aspirated V10 with the Lamborghini Huracán, the Audi R8 delivers sensational sound and everyday-friendly all-weather usability in a striking package.",
  },

  // ---- LUXURY / GRAND TOURERS ----
  {
    id: "rolls-royce-phantom",
    brand: "Rolls-Royce",
    model: "Phantom",
    generation: "Series VIII",
    year: 2022,
    categories: ["luxury"],
    body: "Sedan",
    price: 460000,
    engine: "6.75L Twin-Turbo V12",
    fuel: "Petrol",
    hp: 563,
    torque: 900,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 5.3,
    topSpeed: 250,
    weight: 2560,
    image: px(11770448, 1400, 900),
    gallery: [px(11770448, 1400, 900)],
    tagline: "The pinnacle of automotive luxury.",
    overview:
      "The Phantom is the flagship of bespoke motoring — a silent, V12-propelled sanctuary with a 'magic carpet' ride and the finest handcrafted interior in the industry.",
  },
  {
    id: "bentley-continental-gt",
    brand: "Bentley",
    model: "Continental GT",
    generation: "Gen 3",
    year: 2022,
    categories: ["luxury", "sports"],
    body: "Coupe",
    price: 225000,
    engine: "6.0L Twin-Turbo W12",
    fuel: "Petrol",
    hp: 650,
    torque: 900,
    transmission: "Dual-clutch",
    drivetrain: "AWD",
    zeroToHundred: 3.6,
    topSpeed: 335,
    weight: 2244,
    image: px(16124126, 1400, 900),
    gallery: [px(16124126, 1400, 900)],
    tagline: "Grand touring, redefined in W12 form.",
    overview:
      "The Continental GT blends a 650 hp twin-turbo W12 with a beautifully crafted cabin, delivering continent-crossing performance wrapped in effortless British luxury.",
  },
  {
    id: "mercedes-s-class",
    brand: "Mercedes-Benz",
    model: "S-Class",
    generation: "W223",
    year: 2023,
    categories: ["luxury", "daily"],
    body: "Sedan",
    price: 118000,
    engine: "3.0L Turbo I6 (Mild Hybrid)",
    fuel: "Hybrid",
    hp: 429,
    torque: 520,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 4.9,
    topSpeed: 250,
    weight: 2050,
    image: px(13324313, 1400, 900),
    gallery: [px(13324313, 1400, 900), px(20123558, 1200, 800)],
    tagline: "The benchmark luxury sedan.",
    overview:
      "For decades the S-Class has defined the executive luxury segment, pairing serene ride quality with cutting-edge technology and superlative refinement.",
  },
  {
    id: "lexus-ls",
    brand: "Lexus",
    model: "LS 500",
    generation: "XF50",
    year: 2022,
    categories: ["luxury", "daily"],
    body: "Sedan",
    price: 78000,
    engine: "3.5L Twin-Turbo V6",
    fuel: "Petrol",
    hp: 416,
    torque: 600,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 4.6,
    topSpeed: 250,
    weight: 2190,
    image: px(10029873, 1400, 900),
    gallery: [px(10029873, 1400, 900)],
    tagline: "Japanese omotenashi, in sedan form.",
    overview:
      "Lexus's flagship LS 500 blends a twin-turbo V6 with obsessive build quality and signature Japanese hospitality for a genuinely distinctive luxury experience.",
  },
  {
    id: "bmw-7-series",
    brand: "BMW",
    model: "7 Series",
    generation: "G70",
    year: 2023,
    categories: ["luxury", "daily"],
    body: "Sedan",
    price: 93000,
    engine: "3.0L Turbo I6 (Mild Hybrid)",
    fuel: "Hybrid",
    hp: 375,
    torque: 520,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 5.2,
    topSpeed: 250,
    weight: 2100,
    image: px(29580161, 1400, 900),
    gallery: [px(29580161, 1400, 900), px(29580174, 1200, 800)],
    tagline: "The tech-forward luxury flagship.",
    overview:
      "The seventh-generation 7 Series combines a commanding presence with a theatre-like interior and advanced assisted driving, positioning BMW at the forefront of luxury innovation.",
  },

  // ---- SPORTS / PERFORMANCE ----
  {
    id: "bmw-m3-competition",
    brand: "BMW",
    model: "M3 Competition",
    generation: "G80",
    year: 2023,
    categories: ["sports", "daily"],
    body: "Sedan",
    price: 76000,
    engine: "3.0L Twin-Turbo I6",
    fuel: "Petrol",
    hp: 510,
    torque: 650,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.5,
    topSpeed: 290,
    weight: 1780,
    image: px(29580174, 1400, 900),
    gallery: [px(29580174, 1400, 900), px(10879635, 1200, 800)],
    tagline: "The definitive high-performance sports sedan.",
    overview:
      "The G80 M3 Competition pairs 510 hp with a choice of rear- or all-wheel drive, delivering track-ready pace with genuine daily practicality.",
  },
  {
    id: "bmw-m4-competition",
    brand: "BMW",
    model: "M4 Competition",
    generation: "G82",
    year: 2023,
    categories: ["sports"],
    body: "Coupe",
    price: 79000,
    engine: "3.0L Twin-Turbo I6",
    fuel: "Petrol",
    hp: 510,
    torque: 650,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 3.9,
    topSpeed: 290,
    weight: 1725,
    image: px(10879635, 1400, 900),
    gallery: [px(10879635, 1400, 900), px(29580174, 1200, 800)],
    tagline: "The M3's sharper two-door cousin.",
    overview:
      "The M4 Competition shares the M3's mighty twin-turbo six in a sleeker coupe silhouette, offering razor-sharp dynamics and unmistakable BMW M character.",
  },
  {
    id: "ford-mustang-gt",
    brand: "Ford",
    model: "Mustang GT",
    generation: "S550",
    year: 2022,
    categories: ["sports", "classic"],
    body: "Coupe",
    price: 42000,
    engine: "5.0L NA V8",
    fuel: "Petrol",
    hp: 460,
    torque: 570,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 4.6,
    topSpeed: 249,
    weight: 1740,
    image: px(37508222, 1400, 900),
    gallery: [px(37508222, 1400, 900), px(24182221, 1200, 800), px(37144084, 1200, 800)],
    tagline: "The American muscle car icon.",
    overview:
      "The Mustang GT's 5.0L Coyote V8 delivers thunderous performance and unmistakable character, keeping the American pony-car legend alive for a new generation.",
  },
  {
    id: "ford-mustang-gt500",
    brand: "Ford",
    model: "Mustang Shelby GT500",
    generation: "S550",
    year: 2022,
    categories: ["sports", "supercar"],
    body: "Coupe",
    price: 80000,
    engine: "5.2L Supercharged V8",
    fuel: "Petrol",
    hp: 760,
    torque: 847,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 3.4,
    topSpeed: 290,
    weight: 1920,
    image: px(24182221, 1400, 900),
    gallery: [px(24182221, 1400, 900), px(37508222, 1200, 800)],
    tagline: "760 supercharged horsepower from Shelby.",
    overview:
      "The range-topping Shelby GT500 unleashes 760 hp from a supercharged 5.2L V8, blending quarter-mile ferocity with a sophisticated dual-clutch gearbox.",
  },
  {
    id: "chevrolet-corvette-c8",
    brand: "Chevrolet",
    model: "Corvette C8",
    generation: "C8",
    year: 2023,
    categories: ["sports", "supercar"],
    body: "Coupe",
    price: 68000,
    engine: "6.2L NA V8",
    fuel: "Petrol",
    hp: 495,
    torque: 637,
    transmission: "Dual-clutch",
    drivetrain: "RWD",
    zeroToHundred: 2.9,
    topSpeed: 312,
    weight: 1655,
    image: px(30090368, 1400, 900),
    gallery: [px(30090368, 1400, 900)],
    tagline: "Mid-engine supercar performance, GM value.",
    overview:
      "The eighth-generation Corvette moved its V8 behind the driver, delivering genuine supercar pace and handling at a remarkable price point — a true American icon reborn.",
  },
  {
    id: "dodge-challenger-hellcat",
    brand: "Dodge",
    model: "Challenger SRT Hellcat",
    generation: "LA",
    year: 2022,
    categories: ["sports", "classic"],
    body: "Coupe",
    price: 62000,
    engine: "6.2L Supercharged V8",
    fuel: "Petrol",
    hp: 717,
    torque: 889,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 3.6,
    topSpeed: 320,
    weight: 2010,
    image: px(34071036, 1400, 900),
    gallery: [px(34071036, 1400, 900)],
    tagline: "717 hp of pure American muscle.",
    overview:
      "The Challenger Hellcat's supercharged 6.2L HEMI V8 pumps out 717 hp, delivering brutal straight-line performance with retro-modern muscle-car style.",
  },
  {
    id: "subaru-wrx-sti",
    brand: "Subaru",
    model: "WRX STI",
    generation: "VA",
    year: 2021,
    categories: ["jdm", "sports", "daily"],
    body: "Sedan",
    price: 38000,
    engine: "2.5L Turbo Flat-4 (Boxer)",
    fuel: "Petrol",
    hp: 310,
    torque: 393,
    transmission: "Manual",
    drivetrain: "AWD",
    zeroToHundred: 5.2,
    topSpeed: 255,
    weight: 1550,
    image: px(35831596, 1400, 900),
    gallery: [px(35831596, 1400, 900)],
    tagline: "Rally-bred AWD performance.",
    overview:
      "Born from World Rally Championship success, the WRX STI pairs a turbocharged boxer engine with legendary symmetrical AWD for sure-footed performance in any condition.",
  },

  // ---- SUVs ----
  {
    id: "range-rover-autobiography",
    brand: "Land Rover",
    model: "Range Rover",
    generation: "L460",
    year: 2023,
    categories: ["suv", "luxury", "offroad"],
    body: "SUV",
    price: 108000,
    engine: "4.4L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 530,
    torque: 750,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 4.6,
    topSpeed: 250,
    weight: 2500,
    image: px(31574920, 1400, 900),
    gallery: [px(31574920, 1400, 900), px(31574925, 1200, 800), px(37675872, 1200, 800)],
    tagline: "The original luxury SUV, perfected.",
    overview:
      "The Range Rover remains the defining luxury off-roader, blending a serene V8-powered ride with genuine go-anywhere capability and a minimalist, tech-rich cabin.",
  },
  {
    id: "land-rover-defender",
    brand: "Land Rover",
    model: "Defender 110",
    generation: "L663",
    year: 2022,
    categories: ["suv", "offroad"],
    body: "SUV",
    price: 61000,
    engine: "3.0L Turbo I6 (Mild Hybrid)",
    fuel: "Hybrid",
    hp: 395,
    torque: 550,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 6.2,
    topSpeed: 240,
    weight: 2410,
    image: px(9993526, 1400, 900),
    gallery: [px(9993526, 1400, 900)],
    tagline: "A legend reborn for the modern age.",
    overview:
      "The new Defender reinterprets the iconic off-roader with modern refinement, retaining remarkable capability while adding contemporary comfort and technology.",
  },
  {
    id: "jeep-wrangler-rubicon",
    brand: "Jeep",
    model: "Wrangler Rubicon",
    generation: "JL",
    year: 2022,
    categories: ["offroad", "suv"],
    body: "SUV",
    price: 48000,
    engine: "3.6L NA V6",
    fuel: "Petrol",
    hp: 285,
    torque: 353,
    transmission: "Manual",
    drivetrain: "4WD",
    zeroToHundred: 7.5,
    topSpeed: 180,
    weight: 1900,
    image: px(9993526, 1400, 900),
    gallery: [px(9993526, 1400, 900)],
    tagline: "The definitive off-road icon.",
    overview:
      "The Wrangler Rubicon is engineered for extreme terrain with locking differentials, disconnecting sway bars and rock-crawling gearing — the ultimate open-air adventurer.",
  },
  {
    id: "porsche-cayenne-turbo",
    brand: "Porsche",
    model: "Cayenne Turbo",
    generation: "E3",
    year: 2023,
    categories: ["suv", "luxury", "sports"],
    body: "SUV",
    price: 146000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 631,
    torque: 850,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.9,
    topSpeed: 300,
    weight: 2260,
    image: px(31574925, 1400, 900),
    gallery: [px(31574925, 1400, 900), px(31574920, 1200, 800)],
    tagline: "A sports car wearing an SUV body.",
    overview:
      "Porsche's Cayenne Turbo hides genuine sports-car potency beneath its SUV silhouette, delivering 631 hp and benchmark handling in the luxury performance segment.",
  },
  {
    id: "mercedes-g63-amg",
    brand: "Mercedes-AMG",
    model: "G 63",
    generation: "W463",
    year: 2023,
    categories: ["suv", "offroad", "luxury"],
    body: "SUV",
    price: 180000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 577,
    torque: 850,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 4.5,
    topSpeed: 240,
    weight: 2560,
    image: px(13324313, 1400, 800),
    gallery: [px(13324313, 1400, 900)],
    tagline: "A G-Wagen with AMG fury.",
    overview:
      "The G 63 pairs the G-Class's legendary boxy silhouette and off-road capability with a hand-built AMG V8, creating a uniquely commanding luxury icon.",
  },
  {
    id: "genesis-gv80",
    brand: "Genesis",
    model: "GV80",
    generation: "JX1",
    year: 2023,
    categories: ["suv", "luxury"],
    body: "SUV",
    price: 58000,
    engine: "3.5L Twin-Turbo V6",
    fuel: "Petrol",
    hp: 375,
    torque: 530,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 5.5,
    topSpeed: 240,
    weight: 2180,
    image: px(20430089, 1400, 900),
    gallery: [px(20430089, 1400, 900)],
    tagline: "Korean luxury, boldly designed.",
    overview:
      "Genesis's GV80 brought the young luxury brand global attention with striking design, a sumptuous interior and refined dynamics at a compelling price.",
  },

  // ---- ELECTRIC ----
  {
    id: "tesla-model-s-plaid",
    brand: "Tesla",
    model: "Model S Plaid",
    generation: "Palladium",
    year: 2023,
    categories: ["electric", "luxury", "supercar"],
    body: "Sedan",
    price: 90000,
    engine: "Tri-Motor Electric",
    fuel: "Electric",
    hp: 1020,
    torque: 1420,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 2.1,
    topSpeed: 322,
    weight: 2162,
    image: px(10029873, 1400, 900),
    gallery: [px(10029873, 1400, 900), px(35736779, 1200, 800)],
    tagline: "1,020 hp. The electric benchmark.",
    overview:
      "The Model S Plaid's tri-motor setup produces a staggering 1,020 hp and a 2.1-second sprint to 100 km/h, redefining expectations for electric performance sedans.",
  },
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3 Long Range",
    generation: "Highland",
    year: 2024,
    categories: ["electric", "daily"],
    body: "Sedan",
    price: 48000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 450,
    torque: 520,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 4.2,
    topSpeed: 201,
    weight: 1830,
    image: px(35736779, 1400, 900),
    gallery: [px(35736779, 1400, 900), px(10029873, 1200, 800), px(35736771, 1200, 800)],
    tagline: "The electric sedan that changed everything.",
    overview:
      "The Model 3 democratized premium electric motoring with impressive range, brisk acceleration and a minimalist, software-first interior.",
  },
  {
    id: "porsche-taycan-turbo-s",
    brand: "Porsche",
    model: "Taycan Turbo S",
    generation: "J1",
    year: 2023,
    categories: ["electric", "sports", "luxury"],
    body: "Sedan",
    price: 188000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 761,
    torque: 1050,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 2.8,
    topSpeed: 260,
    weight: 2295,
    image: px(30306584, 1400, 900),
    gallery: [px(30306584, 1400, 900), px(35736771, 1200, 800)],
    tagline: "The electric sports car with soul.",
    overview:
      "Porsche's first electric sports car, the Taycan Turbo S, delivers up to 761 hp with 800-volt architecture and handling precision befitting the Porsche crest.",
  },
  {
    id: "nio-et7",
    brand: "NIO",
    model: "ET7",
    generation: "Gen 2",
    year: 2023,
    categories: ["electric", "luxury"],
    body: "Sedan",
    price: 70000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 653,
    torque: 850,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.8,
    topSpeed: 200,
    weight: 2400,
    image: px(35736771, 1400, 900),
    gallery: [px(35736771, 1400, 900)],
    tagline: "Performance EV with swappable batteries.",
    overview:
      "NIO's ET7 flagship combines 653 hp with the company's innovative battery-swapping network, offering a distinctively premium electric sedan experience.",
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "Seal",
    generation: "Ocean Series",
    year: 2024,
    categories: ["electric", "sports", "daily"],
    body: "Sedan",
    price: 48000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 523,
    torque: 670,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.8,
    topSpeed: 180,
    weight: 2085,
    image: px(33229798, 1400, 900),
    gallery: [px(33229798, 1400, 900)],
    tagline: "Affordable electric performance from China.",
    overview:
      "BYD's Seal brings dual-motor performance and sleek aerodynamics to the mainstream EV market, showcasing the speed of Chinese electric innovation.",
  },

  // ---- JDM ----
  {
    id: "mazda-rx7-fd",
    brand: "Mazda",
    model: "RX-7 FD",
    generation: "FD3S",
    year: 2002,
    categories: ["jdm", "classic", "sports"],
    body: "Coupe",
    price: 65000,
    engine: "1.3L Twin-Turbo Rotary",
    fuel: "Petrol",
    hp: 280,
    torque: 314,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 5.3,
    topSpeed: 250,
    weight: 1270,
    image: px(12954631, 1400, 900),
    gallery: [px(12954631, 1400, 900)],
    tagline: "The rotary icon of the JDM golden era.",
    overview:
      "The FD RX-7's twin-turbo 13B rotary engine and near-perfect front-mid layout made it a legend of the JDM sports car golden age.",
  },
  {
    id: "honda-nsx",
    brand: "Honda",
    model: "NSX",
    generation: "NA1",
    year: 1995,
    categories: ["jdm", "classic", "sports"],
    body: "Coupe",
    price: 90000,
    engine: "3.0L NA V6",
    fuel: "Petrol",
    hp: 270,
    torque: 285,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 5.7,
    topSpeed: 270,
    weight: 1370,
    image: px(30570357, 1400, 900),
    gallery: [px(30570357, 1400, 900)],
    tagline: "The everyday supercar, engineered by Honda.",
    overview:
      "Developed with input from Ayrton Senna, the original NSX proved a supercar could be reliable and everyday-usable while delivering razor-sharp balance.",
  },
  {
    id: "mitsubishi-evo-ix",
    brand: "Mitsubishi",
    model: "Lancer Evolution IX",
    generation: "CT9A",
    year: 2006,
    categories: ["jdm", "sports"],
    body: "Sedan",
    price: 35000,
    engine: "2.0L Turbo I4",
    fuel: "Petrol",
    hp: 286,
    torque: 392,
    transmission: "Manual",
    drivetrain: "AWD",
    zeroToHundred: 5.1,
    topSpeed: 250,
    weight: 1450,
    image: px(16896057, 1400, 900),
    gallery: [px(16896057, 1400, 900)],
    tagline: "Rally-winning AWD turbo performance.",
    overview:
      "The Lancer Evolution IX's turbocharged 4G63 engine and sophisticated AWD made it a rally stages hero and a street performance icon.",
  },
  {
    id: "toyota-gr86",
    brand: "Toyota",
    model: "GR86",
    generation: "ZN8",
    year: 2023,
    categories: ["jdm", "sports", "daily"],
    body: "Coupe",
    price: 30000,
    engine: "2.4L NA Flat-4 (Boxer)",
    fuel: "Petrol",
    hp: 228,
    torque: 250,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 6.1,
    topSpeed: 226,
    weight: 1280,
    image: px(34258634, 1400, 900),
    gallery: [px(34258634, 1400, 900)],
    tagline: "Pure, accessible rear-drive joy.",
    overview:
      "The GR86 is a lightweight, rear-wheel-drive sports car co-developed with Subaru, celebrating the simple pleasure of balanced, affordable driving dynamics.",
  },

  // ---- CLASSICS ----
  {
    id: "ford-mustang-1967",
    brand: "Ford",
    model: "Mustang Fastback",
    generation: "1st Gen",
    year: 1967,
    categories: ["classic"],
    body: "Coupe",
    price: 90000,
    engine: "4.7L NA V8",
    fuel: "Petrol",
    hp: 271,
    torque: 424,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 6.5,
    topSpeed: 200,
    weight: 1270,
    image: px(37508222, 1400, 900),
    gallery: [px(37508222, 1400, 900), px(36816059, 1200, 800)],
    tagline: "The fastback that launched a legend.",
    overview:
      "The 1967 Mustang Fastback epitomizes the original pony-car era, delivering V8 performance in an instantly iconic, endlessly collectible silhouette.",
  },
  {
    id: "chevrolet-camaro-1969",
    brand: "Chevrolet",
    model: "Camaro SS",
    generation: "1st Gen",
    year: 1969,
    categories: ["classic"],
    body: "Coupe",
    price: 85000,
    engine: "6.5L NA V8",
    fuel: "Petrol",
    hp: 375,
    torque: 563,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 6.0,
    topSpeed: 210,
    weight: 1520,
    image: px(30090368, 1400, 900),
    gallery: [px(30090368, 1400, 900)],
    tagline: "American muscle at its peak.",
    overview:
      "The 1969 Camaro SS with its big-block V8 remains one of the most coveted American muscle cars ever produced — raw, powerful and instantly recognizable.",
  },
  {
    id: "lamborghini-countach",
    brand: "Lamborghini",
    model: "Countach",
    generation: "LP400",
    year: 1985,
    categories: ["classic", "supercar"],
    body: "Coupe",
    price: 500000,
    engine: "5.2L NA V12",
    fuel: "Petrol",
    hp: 455,
    torque: 500,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 4.9,
    topSpeed: 290,
    weight: 1490,
    image: px(31124681, 1400, 900),
    gallery: [px(31124681, 1400, 900)],
    tagline: "The exotic wedge that defined an era.",
    overview:
      "The Countach's scissor doors and razor-edged wedge silhouette made it the definitive poster car of the 1980s and a landmark in supercar history.",
  },
  {
    id: "porsche-911-turbo-classic",
    brand: "Porsche",
    model: "911 Carrera RS",
    generation: "930",
    year: 1973,
    categories: ["classic", "sports"],
    body: "Coupe",
    price: 400000,
    engine: "2.7L NA Flat-6",
    fuel: "Petrol",
    hp: 210,
    torque: 255,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 5.8,
    topSpeed: 245,
    weight: 975,
    image: px(38234790, 1400, 900),
    gallery: [px(38234790, 1400, 900)],
    tagline: "The legendary 'ducktail' 911.",
    overview:
      "The 1973 Carrera RS is revered as one of the greatest 911s ever, its lightweight build and signature ducktail spoiler making it an automotive collector's grail.",
  },
  {
    id: "mercedes-300sl",
    brand: "Mercedes-Benz",
    model: "300 SL Gullwing",
    generation: "W198",
    year: 1957,
    categories: ["classic", "luxury"],
    body: "Coupe",
    price: 1500000,
    engine: "3.0L NA I6",
    fuel: "Petrol",
    hp: 215,
    torque: 275,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 7.5,
    topSpeed: 250,
    weight: 1295,
    image: px(16120588, 1400, 900),
    gallery: [px(16120588, 1400, 900), px(32334957, 1200, 800)],
    tagline: "The legendary Gullwing grand tourer.",
    overview:
      "With its signature gullwing doors and fuel-injected straight-six, the 300 SL was the fastest production car of its era and remains an automotive masterpiece.",
  },
  {
    id: "bmw-e30-m3",
    brand: "BMW",
    model: "E30 M3",
    generation: "E30",
    year: 1990,
    categories: ["classic", "sports"],
    body: "Coupe",
    price: 120000,
    engine: "2.3L NA I4",
    fuel: "Petrol",
    hp: 200,
    torque: 240,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 6.9,
    topSpeed: 235,
    weight: 1200,
    image: px(27993136, 1400, 900),
    gallery: [px(27993136, 1400, 900), px(16040403, 1200, 800)],
    tagline: "The boxy coupe that became an icon.",
    overview:
      "Built for touring car racing, the E30 M3's four-cylinder engine and flared arches created one of the most successful and beloved homologation specials of all time.",
  },

  // ---- DAILY / EVERYDAY ----
  {
    id: "volkswagen-golf-gti",
    brand: "Volkswagen",
    model: "Golf GTI",
    generation: "Mk8",
    year: 2023,
    categories: ["daily", "sports"],
    body: "Hatchback",
    price: 31000,
    engine: "2.0L Turbo I4",
    fuel: "Petrol",
    hp: 245,
    torque: 370,
    transmission: "Dual-clutch",
    drivetrain: "FWD",
    zeroToHundred: 6.3,
    topSpeed: 250,
    weight: 1460,
    image: px(7412624, 1400, 900),
    gallery: [px(7412624, 1400, 900), px(7412619, 1200, 800)],
    tagline: "The hot hatch that started it all.",
    overview:
      "The Golf GTI defined the hot-hatch segment, blending everyday practicality with genuinely entertaining performance across more than four decades.",
  },
  {
    id: "honda-civic-type-r",
    brand: "Honda",
    model: "Civic Type R",
    generation: "FL5",
    year: 2023,
    categories: ["daily", "sports", "jdm"],
    body: "Hatchback",
    price: 44000,
    engine: "2.0L Turbo I4",
    fuel: "Petrol",
    hp: 315,
    torque: 420,
    transmission: "Manual",
    drivetrain: "FWD",
    zeroToHundred: 5.4,
    topSpeed: 275,
    weight: 1430,
    image: px(33326197, 1400, 900),
    gallery: [px(33326197, 1400, 900)],
    tagline: "The front-drive Nürburgring record holder.",
    overview:
      "The FL5 Civic Type R set front-wheel-drive lap records at the Nürburgring, delivering astonishing grip and driver engagement in a practical five-door package.",
  },
  {
    id: "mazda-mx5-miata",
    brand: "Mazda",
    model: "MX-5 Miata",
    generation: "ND2",
    year: 2023,
    categories: ["daily", "sports", "jdm"],
    body: "Convertible",
    price: 28000,
    engine: "2.0L NA I4",
    fuel: "Petrol",
    hp: 181,
    torque: 205,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 6.7,
    topSpeed: 219,
    weight: 1050,
    image: px(33229798, 1400, 900),
    gallery: [px(33229798, 1400, 900)],
    tagline: "The best-selling roadster of all time.",
    overview:
      "The MX-5 Miata distills the joy of driving into a lightweight, rear-wheel-drive roadster — the purest expression of affordable motoring pleasure.",
  },
  {
    id: "toyota-corolla",
    brand: "Toyota",
    model: "Corolla",
    generation: "E210",
    year: 2024,
    categories: ["daily"],
    body: "Sedan",
    price: 22000,
    engine: "1.8L NA I4",
    fuel: "Petrol",
    hp: 139,
    torque: 171,
    transmission: "CVT",
    drivetrain: "FWD",
    zeroToHundred: 9.0,
    topSpeed: 195,
    weight: 1350,
    image: px(7412619, 1400, 900),
    gallery: [px(7412619, 1400, 900)],
    tagline: "The world's best-selling car.",
    overview:
      "The Corolla's legendary reliability and efficiency have made it the best-selling nameplate in automotive history, beloved across every continent.",
  },
  {
    id: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    generation: "Gen 1",
    year: 2023,
    categories: ["electric", "daily", "suv"],
    body: "Crossover",
    price: 45000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 320,
    torque: 605,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 5.1,
    topSpeed: 185,
    weight: 2060,
    image: px(29807888, 1400, 900),
    gallery: [px(29807888, 1400, 900)],
    tagline: "Retro-futuristic electric crossover.",
    overview:
      "Hyundai's Ioniq 5 pairs striking 1980s-inspired retro design with 800-volt fast charging and a spacious, lounge-like cabin.",
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6",
    generation: "CV",
    year: 2023,
    categories: ["electric", "daily"],
    body: "Crossover",
    price: 49000,
    engine: "Dual-Motor Electric",
    fuel: "Electric",
    hp: 576,
    torque: 740,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.5,
    topSpeed: 260,
    weight: 2110,
    image: px(29807888, 1400, 900),
    gallery: [px(29807888, 1400, 900)],
    tagline: "The EV6 GT's 576 hp surprises all.",
    overview:
      "Kia's EV6 GT is a genuine performance EV, its dual motors delivering 576 hp and supercar-rivalling acceleration in a stylish crossover body.",
  },
  {
    id: "jaguar-f-type",
    brand: "Jaguar",
    model: "F-Type R",
    generation: "X152",
    year: 2022,
    categories: ["sports", "luxury"],
    body: "Coupe",
    price: 105000,
    engine: "5.0L Supercharged V8",
    fuel: "Petrol",
    hp: 575,
    torque: 700,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.7,
    topSpeed: 300,
    weight: 1720,
    image: px(9411653, 1400, 900),
    gallery: [px(9411653, 1400, 900)],
    tagline: "The British sports car's final V8 roar.",
    overview:
      "The F-Type R's supercharged V8 delivers thunderous sound and serious pace, marking the end of an era for Jaguar's celebrated sports car.",
  },
  {
    id: "alfa-romeo-giulia-qv",
    brand: "Alfa Romeo",
    model: "Giulia Quadrifoglio",
    generation: "952",
    year: 2023,
    categories: ["sports", "luxury", "daily"],
    body: "Sedan",
    price: 81000,
    engine: "2.9L Twin-Turbo V6",
    fuel: "Petrol",
    hp: 505,
    torque: 600,
    transmission: "Automatic",
    drivetrain: "RWD",
    zeroToHundred: 3.9,
    topSpeed: 307,
    weight: 1660,
    image: px(11205815, 1400, 900),
    gallery: [px(11205815, 1400, 900)],
    tagline: "Ferrari DNA in a four-door.",
    overview:
      "The Giulia Quadrifoglio sources its twin-turbo V6 from Ferrari engineering, delivering exotic performance and Italian passion in a sports sedan.",
  },
  {
    id: "lotus-emira",
    brand: "Lotus",
    model: "Emira",
    generation: "Type 131",
    year: 2023,
    categories: ["sports"],
    body: "Coupe",
    price: 95000,
    engine: "3.5L Supercharged V6",
    fuel: "Petrol",
    hp: 400,
    torque: 420,
    transmission: "Manual",
    drivetrain: "RWD",
    zeroToHundred: 4.3,
    topSpeed: 290,
    weight: 1405,
    image: px(38412217, 1400, 900),
    gallery: [px(38412217, 1400, 900)],
    tagline: "Lightweight purism, beautifully packaged.",
    overview:
      "The Lotus Emira is the marque's final petrol-powered model, wrapping Lotus's legendary lightweight philosophy in a striking, road-focused coupe.",
  },
  {
    id: "audi-rs6-avant",
    brand: "Audi",
    model: "RS6 Avant",
    generation: "C8",
    year: 2023,
    categories: ["daily", "sports", "luxury"],
    body: "Wagon",
    price: 125000,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    hp: 621,
    torque: 850,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 3.6,
    topSpeed: 305,
    weight: 2080,
    image: px(20430089, 1400, 900),
    gallery: [px(20430089, 1400, 900)],
    tagline: "The ultimate supercar wagon.",
    overview:
      "The RS6 Avant combines a 621 hp twin-turbo V8 with genuine load-lugging practicality, creating the quintessential high-performance family car.",
  },
  {
    id: "volvo-xc90",
    brand: "Volvo",
    model: "XC90",
    generation: "SPA",
    year: 2023,
    categories: ["suv", "luxury", "daily"],
    body: "SUV",
    price: 57000,
    engine: "2.0L Turbo+Supercharged I4 (Hybrid)",
    fuel: "Hybrid",
    hp: 400,
    torque: 640,
    transmission: "Automatic",
    drivetrain: "AWD",
    zeroToHundred: 5.8,
    topSpeed: 210,
    weight: 2200,
    image: px(20430089, 1400, 900),
    gallery: [px(20430089, 1400, 900)],
    tagline: "Scandinavian safety and design.",
    overview:
      "Volvo's XC90 blends Scandinavian minimalism, class-leading safety and a refined plug-in hybrid powertrain into a serene family SUV.",
  },
];

// ============================================================
// CATEGORY LABELS + UNIQUE BRANDS + BODY TYPES (for filters)
// ============================================================
export const categoryList: { id: Category; key: string }[] = [
  { id: "supercar", key: "cat_supercar" },
  { id: "sports", key: "cat_sports" },
  { id: "luxury", key: "cat_luxury2" },
  { id: "suv", key: "cat_suv" },
  { id: "electric", key: "cat_electric" },
  { id: "jdm", key: "cat_jdm" },
  { id: "classic", key: "cat_classic" },
  { id: "offroad", key: "cat_offroad" },
  { id: "daily", key: "cat_daily" },
];

export function categoryKey(cat: Category): string {
  const found = categoryList.find((c) => c.id === cat);
  return found?.key ?? "cat_daily";
}

export type SortKey = "popular" | "newest" | "fastest" | "cheapest" | "powerful";
