// GENERATED by scripts/generate-counts.mjs at prebuild — do not edit.
// Live database counts, frozen from the real data at build time so the
// hero can render them without shipping the car/story datasets to every
// route. `npm run build` regenerates this file; the prerendered HTML
// and these numbers are stamped from the same snapshot.
export const COUNTS = {
  cars: 509,
  brands: 66,
  stories: 25,
  categories: 9,
} as const;
