// ============================================================
// CARVIBES — Used Cars guide (2026–2027)
//
// A curated, editorial layer on top of the real vehicle database.
// Every pick references an existing `Car` id, so each card can deep-link
// to /car/:id, reuse its image and never drift away from the database.
//
// Scores are 0–100 editorial estimates (reliability, maintenance cost,
// fuel economy, performance, value) for the used market in 2026–2027.
// The CarVibes Score is a weighted blend — see `usedCarScore()`.
// ============================================================
import type { Car } from "./cars";
import { cars } from "./db";

export type UsedCategoryId =
  | "reliable"
  | "budget"
  | "suv"
  | "sports"
  | "luxury"
  | "family"
  | "hybrid"
  | "ev"
  | "efficient";

export interface UsedCategory {
  id: UsedCategoryId;
  emoji: string;
  /** Short label used on the category cards / chips. */
  label: string;
  /** Full H2 title used in the results section. */
  title: string;
  description: string;
}

export const USED_CATEGORIES: UsedCategory[] = [
  {
    id: "reliable",
    emoji: "🛡️",
    label: "Most Reliable",
    title: "Most Reliable Used Cars",
    description:
      "Proven drivetrains, low defect rates and owners who keep them for 200,000+ miles.",
  },
  {
    id: "budget",
    emoji: "💰",
    label: "On a Budget",
    title: "Best Used Cars on a Budget",
    description:
      "Maximum car for the money: strong value under $20k without gambling on reliability.",
  },
  {
    id: "suv",
    emoji: "🚙",
    label: "Best SUVs",
    title: "Best Used SUVs",
    description:
      "Space, all-weather confidence and resale strength — the smartest used SUVs to buy now.",
  },
  {
    id: "sports",
    emoji: "🏎️",
    label: "Sports Cars",
    title: "Best Used Sports Cars",
    description:
      "Driver's cars that have already taken their depreciation hit but not lost their edge.",
  },
  {
    id: "luxury",
    emoji: "👑",
    label: "Luxury",
    title: "Best Used Luxury Cars",
    description:
      "Flagship comfort and technology at a fraction of the original sticker price.",
  },
  {
    id: "family",
    emoji: "👨‍👩‍👧",
    label: "Family",
    title: "Best Used Family Cars",
    description:
      "Three rows, top safety scores and interiors built to survive real family life.",
  },
  {
    id: "hybrid",
    emoji: "⚡",
    label: "Hybrids",
    title: "Best Used Hybrid Cars",
    description:
      "Battery systems with a long track record, huge fuel savings and no range anxiety.",
  },
  {
    id: "ev",
    emoji: "🔋",
    label: "EVs",
    title: "Best Used EVs",
    description:
      "Used electric cars with healthy batteries, fast charging and mature software.",
  },
  {
    id: "efficient",
    emoji: "⛽",
    label: "Fuel-Efficient",
    title: "Best Fuel-Efficient Used Cars",
    description:
      "The lowest running costs per mile — hybrids and lean petrol engines that sip fuel.",
  },
];

export interface UsedCarPick {
  /** Must match an id in the CarVibes database. */
  carId: string;
  /** Model-year window we recommend on the used market. */
  years: string;
  /** Estimated used price range (USD) for 2026–2027. */
  priceMin: number;
  priceMax: number;
  /** 0–100 editorial scores. */
  reliability: number;
  maintenance: number; // higher = cheaper / easier to maintain
  fuelEconomy: number;
  performance: number;
  value: number;
  /** Human-readable economy figure ("52 mpg", "~300 mi range"). */
  fuelLabel: string;
  /** One-line verdict. */
  why: string;
  categories: UsedCategoryId[];
}

// Ordered roughly by overall desirability; each category is re-sorted by
// CarVibes Score at runtime so the order here is only a fallback.
export const USED_CAR_PICKS: UsedCarPick[] = [
  {
    carId: "toyota-camry",
    years: "2020–2024",
    priceMin: 17000,
    priceMax: 27000,
    reliability: 96,
    maintenance: 92,
    fuelEconomy: 80,
    performance: 58,
    value: 88,
    fuelLabel: "32 mpg combined",
    why: "The default answer for a dependable mid-size sedan — bulletproof powertrains and cheap parts.",
    categories: ["reliable", "family", "efficient"],
  },
  {
    carId: "toyota-corolla",
    years: "2020–2024",
    priceMin: 14000,
    priceMax: 22000,
    reliability: 97,
    maintenance: 95,
    fuelEconomy: 86,
    performance: 42,
    value: 92,
    fuelLabel: "35 mpg combined",
    why: "Lowest total cost of ownership in its class, with a modern cabin and standard safety tech.",
    categories: ["reliable", "budget", "efficient"],
  },
  {
    carId: "honda-civic",
    years: "2020–2024",
    priceMin: 15000,
    priceMax: 24000,
    reliability: 93,
    maintenance: 91,
    fuelEconomy: 85,
    performance: 55,
    value: 90,
    fuelLabel: "36 mpg combined",
    why: "Sharper to drive than the Corolla and just as durable — the enthusiast's sensible choice.",
    categories: ["reliable", "budget", "efficient"],
  },
  {
    carId: "honda-accord",
    years: "2019–2023",
    priceMin: 17000,
    priceMax: 28000,
    reliability: 92,
    maintenance: 88,
    fuelEconomy: 78,
    performance: 66,
    value: 87,
    fuelLabel: "33 mpg combined",
    why: "Refined, spacious and quietly quick — the 2.0T is one of the best mid-size engines of the decade.",
    categories: ["reliable", "family", "efficient"],
  },
  {
    carId: "mazda-3",
    years: "2019–2024",
    priceMin: 14000,
    priceMax: 23000,
    reliability: 90,
    maintenance: 88,
    fuelEconomy: 80,
    performance: 56,
    value: 86,
    fuelLabel: "31 mpg combined",
    why: "Premium-feeling cabin at compact-car money, with Mazda's reliability record to back it up.",
    categories: ["budget", "efficient"],
  },
  {
    carId: "honda-fit-jazz",
    years: "2018–2023",
    priceMin: 10000,
    priceMax: 17000,
    reliability: 94,
    maintenance: 95,
    fuelEconomy: 88,
    performance: 34,
    value: 93,
    fuelLabel: "36 mpg combined",
    why: "Unbeatable practicality per dollar — the Magic Seat makes it feel bigger than some crossovers.",
    categories: ["budget", "efficient"],
  },
  {
    carId: "subaru-legacy",
    years: "2020–2024",
    priceMin: 15000,
    priceMax: 24000,
    reliability: 86,
    maintenance: 82,
    fuelEconomy: 72,
    performance: 54,
    value: 85,
    fuelLabel: "30 mpg combined",
    why: "Standard all-wheel drive for the price of a front-drive rival, with excellent crash ratings.",
    categories: ["budget", "family"],
  },
  {
    carId: "volkswagen-passat",
    years: "2020–2022",
    priceMin: 13000,
    priceMax: 20000,
    reliability: 80,
    maintenance: 74,
    fuelEconomy: 74,
    performance: 52,
    value: 84,
    fuelLabel: "28 mpg combined",
    why: "Huge rear seat, mature ride and steep depreciation make it a quiet used-market bargain.",
    categories: ["budget"],
  },
  {
    carId: "nissan-altima",
    years: "2021–2024",
    priceMin: 13000,
    priceMax: 21000,
    reliability: 78,
    maintenance: 80,
    fuelEconomy: 78,
    performance: 50,
    value: 83,
    fuelLabel: "32 mpg combined",
    why: "Later model years fixed early CVT worries; look for AWD versions in snow-belt regions.",
    categories: ["budget"],
  },
  {
    carId: "chevrolet-equinox",
    years: "2020–2024",
    priceMin: 14000,
    priceMax: 23000,
    reliability: 80,
    maintenance: 84,
    fuelEconomy: 70,
    performance: 46,
    value: 84,
    fuelLabel: "28 mpg combined",
    why: "One of the cheapest ways into a modern compact SUV, with plentiful parts and easy servicing.",
    categories: ["budget", "suv"],
  },
  {
    carId: "toyota-rav4",
    years: "2019–2024",
    priceMin: 20000,
    priceMax: 32000,
    reliability: 95,
    maintenance: 90,
    fuelEconomy: 82,
    performance: 55,
    value: 86,
    fuelLabel: "40 mpg (Hybrid)",
    why: "The best-selling SUV for a reason — the Hybrid version is the one to buy for 2026–2027.",
    categories: ["reliable", "suv", "hybrid", "family", "efficient"],
  },
  {
    carId: "honda-cr-v",
    years: "2020–2024",
    priceMin: 20000,
    priceMax: 31000,
    reliability: 93,
    maintenance: 89,
    fuelEconomy: 76,
    performance: 52,
    value: 85,
    fuelLabel: "30 mpg combined",
    why: "Class-leading cargo space and a turbo engine that has proven itself over millions of miles.",
    categories: ["reliable", "suv", "family"],
  },
  {
    carId: "mazda-cx-5",
    years: "2019–2024",
    priceMin: 17000,
    priceMax: 29000,
    reliability: 91,
    maintenance: 87,
    fuelEconomy: 70,
    performance: 62,
    value: 88,
    fuelLabel: "27 mpg combined",
    why: "Drives and feels like a premium SUV without the premium repair bills.",
    categories: ["reliable", "suv"],
  },
  {
    carId: "subaru-forester",
    years: "2019–2024",
    priceMin: 17000,
    priceMax: 28000,
    reliability: 88,
    maintenance: 83,
    fuelEconomy: 72,
    performance: 46,
    value: 86,
    fuelLabel: "29 mpg combined",
    why: "Best visibility in the segment, standard AWD and a huge boot — a pragmatic family favourite.",
    categories: ["suv", "family"],
  },
  {
    carId: "subaru-outback",
    years: "2020–2024",
    priceMin: 18000,
    priceMax: 30000,
    reliability: 88,
    maintenance: 82,
    fuelEconomy: 70,
    performance: 54,
    value: 85,
    fuelLabel: "29 mpg combined",
    why: "Wagon practicality, SUV ground clearance and Subaru safety in one long-lived package.",
    categories: ["reliable", "family"],
  },
  {
    carId: "toyota-highlander",
    years: "2020–2024",
    priceMin: 27000,
    priceMax: 40000,
    reliability: 94,
    maintenance: 88,
    fuelEconomy: 74,
    performance: 60,
    value: 82,
    fuelLabel: "36 mpg (Hybrid)",
    why: "The three-row SUV that simply refuses to break; the Hybrid returns small-car fuel economy.",
    categories: ["suv", "family", "hybrid", "reliable"],
  },
  {
    carId: "honda-pilot",
    years: "2019–2023",
    priceMin: 24000,
    priceMax: 37000,
    reliability: 89,
    maintenance: 85,
    fuelEconomy: 60,
    performance: 62,
    value: 83,
    fuelLabel: "22 mpg combined",
    why: "Eight seats, a smooth V6 and minivan-level practicality in an SUV body.",
    categories: ["family", "suv"],
  },
  {
    carId: "chrysler-pacifica",
    years: "2020–2024",
    priceMin: 22000,
    priceMax: 36000,
    reliability: 76,
    maintenance: 76,
    fuelEconomy: 78,
    performance: 55,
    value: 84,
    fuelLabel: "82 MPGe (PHEV)",
    why: "The only plug-in hybrid minivan — 30+ electric miles covers most school runs for free.",
    categories: ["family", "hybrid"],
  },
  {
    carId: "ford-explorer",
    years: "2021–2024",
    priceMin: 24000,
    priceMax: 38000,
    reliability: 74,
    maintenance: 78,
    fuelEconomy: 58,
    performance: 70,
    value: 80,
    fuelLabel: "24 mpg combined",
    why: "Rear-drive platform makes it feel athletic for a three-row; later years are the ones to buy.",
    categories: ["family"],
  },
  {
    carId: "nissan-pathfinder",
    years: "2022–2024",
    priceMin: 25000,
    priceMax: 37000,
    reliability: 80,
    maintenance: 80,
    fuelEconomy: 58,
    performance: 60,
    value: 82,
    fuelLabel: "23 mpg combined",
    why: "The 2022 redesign ditched the CVT for a real 9-speed automatic and gained a much better cabin.",
    categories: ["family"],
  },
  {
    carId: "lexus-rx",
    years: "2019–2023",
    priceMin: 30000,
    priceMax: 46000,
    reliability: 97,
    maintenance: 84,
    fuelEconomy: 76,
    performance: 62,
    value: 80,
    fuelLabel: "30 mpg (Hybrid)",
    why: "Consistently the most reliable luxury SUV on the market — the 450h hybrid is exceptional.",
    categories: ["reliable", "suv", "luxury", "hybrid"],
  },
  {
    carId: "lexus-nx",
    years: "2020–2024",
    priceMin: 27000,
    priceMax: 40000,
    reliability: 95,
    maintenance: 84,
    fuelEconomy: 80,
    performance: 58,
    value: 80,
    fuelLabel: "39 mpg (Hybrid)",
    why: "Compact luxury with Toyota hybrid economy and near-zero unscheduled repairs.",
    categories: ["reliable", "hybrid", "luxury", "efficient"],
  },
  {
    carId: "lexus-ls",
    years: "2018–2022",
    priceMin: 35000,
    priceMax: 55000,
    reliability: 94,
    maintenance: 76,
    fuelEconomy: 54,
    performance: 74,
    value: 84,
    fuelLabel: "23 mpg combined",
    why: "A $100k flagship for half price, and unlike its German rivals it will not bankrupt you at 100k miles.",
    categories: ["luxury", "reliable"],
  },
  {
    carId: "lexus-lc-500",
    years: "2018–2023",
    priceMin: 55000,
    priceMax: 80000,
    reliability: 92,
    maintenance: 72,
    fuelEconomy: 40,
    performance: 86,
    value: 76,
    fuelLabel: "19 mpg combined",
    why: "Naturally aspirated V8 grand tourer with concept-car looks and Lexus dependability.",
    categories: ["luxury", "sports"],
  },
  {
    carId: "genesis-gv80",
    years: "2021–2024",
    priceMin: 35000,
    priceMax: 52000,
    reliability: 85,
    maintenance: 82,
    fuelEconomy: 56,
    performance: 70,
    value: 88,
    fuelLabel: "21 mpg combined",
    why: "Rolls-Royce-inspired cabin for German mid-size money, with a warranty that often transfers.",
    categories: ["luxury", "suv"],
  },
  {
    carId: "mercedes-benz-e-class",
    years: "2020–2023",
    priceMin: 30000,
    priceMax: 48000,
    reliability: 80,
    maintenance: 62,
    fuelEconomy: 62,
    performance: 72,
    value: 80,
    fuelLabel: "26 mpg combined",
    why: "The benchmark executive sedan; budget for a specialist independent and it is a joy to own.",
    categories: ["luxury"],
  },
  {
    carId: "bmw-5-series",
    years: "2020–2023",
    priceMin: 28000,
    priceMax: 46000,
    reliability: 80,
    maintenance: 62,
    fuelEconomy: 64,
    performance: 76,
    value: 82,
    fuelLabel: "27 mpg combined",
    why: "The G30 generation is one of BMW's most dependable — the 530i and 540i are sweet spots.",
    categories: ["luxury"],
  },
  {
    carId: "audi-a6",
    years: "2020–2023",
    priceMin: 28000,
    priceMax: 45000,
    reliability: 78,
    maintenance: 60,
    fuelEconomy: 62,
    performance: 74,
    value: 80,
    fuelLabel: "26 mpg combined",
    why: "Quattro all-weather ability and the best interior tech of the trio — depreciation is your friend.",
    categories: ["luxury"],
  },
  {
    carId: "volvo-xc90",
    years: "2020–2024",
    priceMin: 30000,
    priceMax: 50000,
    reliability: 82,
    maintenance: 68,
    fuelEconomy: 70,
    performance: 68,
    value: 80,
    fuelLabel: "58 MPGe (Recharge)",
    why: "Seven seats, Scandinavian calm and a plug-in option — the family luxury SUV with a conscience.",
    categories: ["luxury", "family", "hybrid", "suv"],
  },
  {
    carId: "bmw-x3",
    years: "2020–2024",
    priceMin: 26000,
    priceMax: 42000,
    reliability: 82,
    maintenance: 66,
    fuelEconomy: 64,
    performance: 72,
    value: 78,
    fuelLabel: "26 mpg combined",
    why: "Handles like a 3 Series on stilts and the B48 2.0-litre has proven itself over a decade.",
    categories: ["suv", "luxury"],
  },
  {
    carId: "audi-q5",
    years: "2021–2024",
    priceMin: 25000,
    priceMax: 40000,
    reliability: 80,
    maintenance: 64,
    fuelEconomy: 64,
    performance: 68,
    value: 78,
    fuelLabel: "25 mpg combined",
    why: "Polished, quiet and well-equipped — the mid-life facelift brought better reliability and screens.",
    categories: ["suv", "luxury"],
  },
  {
    carId: "toyota-4runner",
    years: "2019–2024",
    priceMin: 30000,
    priceMax: 45000,
    reliability: 96,
    maintenance: 88,
    fuelEconomy: 38,
    performance: 50,
    value: 78,
    fuelLabel: "17 mpg combined",
    why: "Old-school body-on-frame toughness that holds value better than almost any vehicle on sale.",
    categories: ["suv", "reliable"],
  },
  {
    carId: "mazda-mx5-miata",
    years: "2019–2024",
    priceMin: 20000,
    priceMax: 30000,
    reliability: 94,
    maintenance: 92,
    fuelEconomy: 78,
    performance: 70,
    value: 92,
    fuelLabel: "30 mpg combined",
    why: "The purest sports car you can buy used — cheap to run, reliable and endlessly fun.",
    categories: ["sports", "reliable", "efficient"],
  },
  {
    carId: "toyota-gr86",
    years: "2022–2024",
    priceMin: 24000,
    priceMax: 31000,
    reliability: 90,
    maintenance: 88,
    fuelEconomy: 66,
    performance: 74,
    value: 90,
    fuelLabel: "25 mpg combined",
    why: "The 2.4-litre finally gave the rear-drive coupé the torque it needed; still under warranty for many.",
    categories: ["sports", "budget"],
  },
  {
    carId: "subaru-brz",
    years: "2022–2024",
    priceMin: 23000,
    priceMax: 30000,
    reliability: 90,
    maintenance: 88,
    fuelEconomy: 66,
    performance: 74,
    value: 89,
    fuelLabel: "25 mpg combined",
    why: "Slightly softer twin of the GR86 with the same balance and bulletproof 6-speed manual.",
    categories: ["sports"],
  },
  {
    carId: "porsche-718-cayman",
    years: "2018–2023",
    priceMin: 45000,
    priceMax: 70000,
    reliability: 88,
    maintenance: 62,
    fuelEconomy: 56,
    performance: 90,
    value: 80,
    fuelLabel: "22 mpg combined",
    why: "Mid-engine precision from the most reliable sports-car maker — the GTS 4.0 is a future classic.",
    categories: ["sports", "luxury"],
  },
  {
    carId: "porsche-911-carrera",
    years: "2020–2023",
    priceMin: 85000,
    priceMax: 115000,
    reliability: 90,
    maintenance: 60,
    fuelEconomy: 50,
    performance: 95,
    value: 74,
    fuelLabel: "20 mpg combined",
    why: "The 992 holds value like a savings account and is usable every single day.",
    categories: ["sports", "luxury"],
  },
  {
    carId: "ford-mustang-gt",
    years: "2019–2023",
    priceMin: 26000,
    priceMax: 40000,
    reliability: 82,
    maintenance: 84,
    fuelEconomy: 40,
    performance: 86,
    value: 88,
    fuelLabel: "18 mpg combined",
    why: "460 hp of naturally aspirated V8 for hot-hatch money — the Coyote engine is famously robust.",
    categories: ["sports"],
  },
  {
    carId: "chevrolet-camaro-ss",
    years: "2019–2023",
    priceMin: 27000,
    priceMax: 40000,
    reliability: 82,
    maintenance: 82,
    fuelEconomy: 38,
    performance: 88,
    value: 86,
    fuelLabel: "19 mpg combined",
    why: "LT1 V8, magnetic dampers and Alpha-platform handling that embarrasses far pricier coupés.",
    categories: ["sports"],
  },
  {
    carId: "chevrolet-corvette-c8",
    years: "2020–2023",
    priceMin: 58000,
    priceMax: 78000,
    reliability: 84,
    maintenance: 70,
    fuelEconomy: 40,
    performance: 96,
    value: 86,
    fuelLabel: "19 mpg combined",
    why: "Mid-engine supercar performance at sports-car prices; early cars are now sensibly priced.",
    categories: ["sports"],
  },
  {
    carId: "honda-civic-type-r",
    years: "2020–2024",
    priceMin: 32000,
    priceMax: 45000,
    reliability: 90,
    maintenance: 84,
    fuelEconomy: 64,
    performance: 86,
    value: 80,
    fuelLabel: "24 mpg combined",
    why: "The fastest front-wheel-drive car you can buy, with Honda's durability and a usable hatch body.",
    categories: ["sports"],
  },
  {
    carId: "volkswagen-golf-gti",
    years: "2019–2024",
    priceMin: 20000,
    priceMax: 32000,
    reliability: 82,
    maintenance: 76,
    fuelEconomy: 70,
    performance: 76,
    value: 88,
    fuelLabel: "27 mpg combined",
    why: "The original all-rounder: quick, refined, practical and cheap to insure for its pace.",
    categories: ["sports", "budget"],
  },
  {
    carId: "bmw-m2",
    years: "2019–2021",
    priceMin: 42000,
    priceMax: 58000,
    reliability: 84,
    maintenance: 66,
    fuelEconomy: 46,
    performance: 92,
    value: 80,
    fuelLabel: "20 mpg combined",
    why: "The M2 Competition's S55 engine and compact footprint make it the last analogue M car.",
    categories: ["sports"],
  },
  {
    carId: "toyota-supra-a90",
    years: "2020–2023",
    priceMin: 38000,
    priceMax: 52000,
    reliability: 88,
    maintenance: 74,
    fuelEconomy: 56,
    performance: 90,
    value: 82,
    fuelLabel: "25 mpg combined",
    why: "BMW B58 power with Toyota backing; manual cars from 2023 are the collector-grade pick.",
    categories: ["sports"],
  },
  {
    carId: "nissan-z",
    years: "2023–2024",
    priceMin: 34000,
    priceMax: 44000,
    reliability: 84,
    maintenance: 80,
    fuelEconomy: 46,
    performance: 88,
    value: 84,
    fuelLabel: "20 mpg combined",
    why: "400 hp twin-turbo V6, a proper manual and retro looks — already priced well below new.",
    categories: ["sports"],
  },
  {
    carId: "toyota-prius",
    years: "2019–2024",
    priceMin: 17000,
    priceMax: 30000,
    reliability: 96,
    maintenance: 90,
    fuelEconomy: 100,
    performance: 42,
    value: 90,
    fuelLabel: "56 mpg combined",
    why: "Three decades of hybrid know-how; the 2023 redesign is finally handsome and quick too.",
    categories: ["hybrid", "efficient", "reliable", "budget"],
  },
  {
    carId: "toyota-c-hr",
    years: "2019–2023",
    priceMin: 15000,
    priceMax: 23000,
    reliability: 92,
    maintenance: 90,
    fuelEconomy: 84,
    performance: 38,
    value: 84,
    fuelLabel: "29 mpg combined",
    why: "Concept-car styling on Toyota's most reliable hybrid platform — ideal for city commuters.",
    categories: ["hybrid", "efficient", "budget"],
  },
  {
    carId: "bmw-x5",
    years: "2021–2024",
    priceMin: 40000,
    priceMax: 60000,
    reliability: 82,
    maintenance: 60,
    fuelEconomy: 70,
    performance: 84,
    value: 78,
    fuelLabel: "50 MPGe (xDrive45e)",
    why: "The xDrive45e plug-in delivers 30+ electric miles and a silky six-cylinder when you need it.",
    categories: ["hybrid", "luxury"],
  },
  {
    carId: "mercedes-benz-gle",
    years: "2021–2024",
    priceMin: 40000,
    priceMax: 62000,
    reliability: 78,
    maintenance: 58,
    fuelEconomy: 62,
    performance: 78,
    value: 76,
    fuelLabel: "23 mpg (mild hybrid)",
    why: "48-volt mild-hybrid straight-six and one of the most comfortable cabins on the road.",
    categories: ["hybrid", "luxury"],
  },
  {
    carId: "tesla-model-3",
    years: "2021–2024",
    priceMin: 22000,
    priceMax: 34000,
    reliability: 84,
    maintenance: 90,
    fuelEconomy: 96,
    performance: 84,
    value: 92,
    fuelLabel: "~130 MPGe · 270–330 mi",
    why: "The used EV benchmark: Supercharger access, minimal maintenance and strong battery longevity.",
    categories: ["ev", "efficient", "budget"],
  },
  {
    carId: "tesla-model-y",
    years: "2021–2024",
    priceMin: 27000,
    priceMax: 40000,
    reliability: 82,
    maintenance: 90,
    fuelEconomy: 92,
    performance: 84,
    value: 88,
    fuelLabel: "~120 MPGe · 280–330 mi",
    why: "Family-sized EV with the industry's best charging network — huge supply keeps prices sane.",
    categories: ["ev", "suv", "family"],
  },
  {
    carId: "hyundai-ioniq-5",
    years: "2022–2024",
    priceMin: 25000,
    priceMax: 38000,
    reliability: 86,
    maintenance: 88,
    fuelEconomy: 88,
    performance: 78,
    value: 88,
    fuelLabel: "~110 MPGe · 260–300 mi",
    why: "800-volt charging (10–80% in 18 min) and a lounge-like cabin; the battery warranty transfers.",
    categories: ["ev", "suv"],
  },
  {
    carId: "kia-ev6",
    years: "2022–2024",
    priceMin: 26000,
    priceMax: 40000,
    reliability: 86,
    maintenance: 88,
    fuelEconomy: 88,
    performance: 84,
    value: 86,
    fuelLabel: "~115 MPGe · 270–310 mi",
    why: "Same ultra-fast-charging platform as the Ioniq 5 in a sportier, lower body.",
    categories: ["ev"],
  },
  {
    carId: "ford-mustang-mach-e",
    years: "2021–2024",
    priceMin: 24000,
    priceMax: 38000,
    reliability: 80,
    maintenance: 86,
    fuelEconomy: 84,
    performance: 82,
    value: 86,
    fuelLabel: "~100 MPGe · 250–310 mi",
    why: "Fun to drive, spacious and now heavily discounted on the used market after price cuts.",
    categories: ["ev", "suv"],
  },
  {
    carId: "volkswagen-id-4",
    years: "2021–2024",
    priceMin: 20000,
    priceMax: 32000,
    reliability: 78,
    maintenance: 86,
    fuelEconomy: 84,
    performance: 62,
    value: 88,
    fuelLabel: "~105 MPGe · 250–275 mi",
    why: "Quiet, roomy and among the cheapest ways into a new-generation EV; 2024 software is much improved.",
    categories: ["ev", "budget"],
  },
  {
    carId: "nissan-leaf",
    years: "2019–2024",
    priceMin: 11000,
    priceMax: 20000,
    reliability: 88,
    maintenance: 92,
    fuelEconomy: 86,
    performance: 50,
    value: 90,
    fuelLabel: "~110 MPGe · 150–215 mi",
    why: "The cheapest usable used EV — perfect as a second car; choose the 62 kWh Plus for range.",
    categories: ["ev", "budget", "efficient"],
  },
  {
    carId: "bmw-i4",
    years: "2022–2024",
    priceMin: 35000,
    priceMax: 50000,
    reliability: 84,
    maintenance: 80,
    fuelEconomy: 86,
    performance: 88,
    value: 80,
    fuelLabel: "~110 MPGe · 270–300 mi",
    why: "Drives like a proper 4 Series with instant torque and BMW build quality.",
    categories: ["ev", "luxury"],
  },
  {
    carId: "audi-q4-e-tron",
    years: "2022–2024",
    priceMin: 28000,
    priceMax: 42000,
    reliability: 80,
    maintenance: 82,
    fuelEconomy: 82,
    performance: 66,
    value: 82,
    fuelLabel: "~95 MPGe · 240–265 mi",
    why: "Audi refinement on the affordable MEB platform — a serene, well-built family EV.",
    categories: ["ev", "luxury"],
  },
  {
    carId: "porsche-taycan",
    years: "2020–2023",
    priceMin: 55000,
    priceMax: 80000,
    reliability: 84,
    maintenance: 62,
    fuelEconomy: 74,
    performance: 96,
    value: 82,
    fuelLabel: "~80 MPGe · 200–240 mi",
    why: "Halved in value since new, the Taycan is now the performance-EV bargain of the decade.",
    categories: ["ev", "luxury", "sports"],
  },
  {
    carId: "mercedes-benz-a-class",
    years: "2019–2023",
    priceMin: 18000,
    priceMax: 28000,
    reliability: 80,
    maintenance: 68,
    fuelEconomy: 78,
    performance: 56,
    value: 80,
    fuelLabel: "31 mpg combined",
    why: "Premium badge and MBUX tech in a frugal compact — the A 200 is the efficient sweet spot.",
    categories: ["efficient", "luxury"],
  },
];

/** Weighted 0–100 CarVibes Score for the used market. */
export function usedCarScore(p: UsedCarPick): number {
  return Math.round(
    p.reliability * 0.3 +
      p.maintenance * 0.2 +
      p.fuelEconomy * 0.2 +
      p.performance * 0.15 +
      p.value * 0.15
  );
}

export interface UsedCarEntry extends UsedCarPick {
  car: Car;
  score: number;
}

const carById = new Map(cars.map((c) => [c.id, c]));

/** All picks joined to their database car (picks with an unknown id are dropped). */
export const USED_CAR_ENTRIES: UsedCarEntry[] = USED_CAR_PICKS.flatMap((p) => {
  const car = carById.get(p.carId);
  return car ? [{ ...p, car, score: usedCarScore(p) }] : [];
});

/** Best entries for a category, highest CarVibes Score first. */
export function usedCarsForCategory(id: UsedCategoryId): UsedCarEntry[] {
  return USED_CAR_ENTRIES.filter((e) => e.categories.includes(id)).sort(
    (a, b) => b.score - a.score
  );
}

export function isUsedCategoryId(v: string | null | undefined): v is UsedCategoryId {
  return !!v && USED_CATEGORIES.some((c) => c.id === v);
}
