// GENERATED by scripts/generate-counts.mjs at prebuild — do not edit.
// Question-bank figures the /car-quiz hub renders WITHOUT importing the
// bank itself (total count + per-quiz max reward, computed from the real
// data by the same functions the player uses). `npm run build`
// regenerates this file; smoke-quiz/validate-quiz re-check the numbers
// against the live bank, so a stale file fails the build pipeline.
export const TOTAL_QUESTIONS = 164;

export const MAX_REWARDS: Record<string, number> = {
  "silhouette": 650,
  "warm-up-lap": 650,
  "pit-lane": 1675,
  "jdm-cult": 1600,
  "german-precision": 1675,
  "silent-power": 1600,
  "first-class": 1600,
  "italian-passion": 2200,
  "apex-predators": 2775,
  "price-tag": 1450,
  "the-gauntlet": 4000,
  "premium-rising-stars": 2100,
  "premium-precision-circuit": 3200,
  "premium-electric-revolution": 2700,
  "premium-german-engineering": 4650,
  "premium-jdm-underground": 4650,
  "premium-auction-block": 1950,
  "premium-ultimate-supercars": 6400,
};
