// ============================================================
// CARVIBES / MARKETVIBES — standalone API server (production)
//
//   npm run marketplace:serve           # PORT=8787 by default
//
// Hosts the exact same handler the dev/preview middleware mounts, so
// nothing behaves differently between the preview the admin tests and
// the deployment. It speaks plain Node http — deploy it to any Node
// host (Railway, Fly.io, Render, a VPS, a container) with a persistent
// volume mounted at MARKETPLACE_DATA_DIR + MARKETPLACE_MEDIA_DIR.
//
// It also serves the uploaded listing photos (MARKETPLACE_MEDIA_DIR)
// under MEDIA_URL_PREFIX, read-only, with traversal guards.
//
// DEPLOYMENT (see docs/MARKETPLACE.md)
// -----------------------------------
// The static site stays on Vercel; this process runs on Railway (single
// replica, persistent volume) and Vercel PROXIES /api/marketplace/* and
// /marketplace-media/* to it. The browser therefore only ever talks to
// the site's own domain: the admin cookie stays first-party, no CORS and
// no SameSite=None are needed, and the client keeps using its default
// same-origin relative API base.
//
// The alternative (split origins) still works: point the UI at this
// server with VITE_MARKETPLACE_API_URL=https://api.example.com/api/marketplace
// and allow the site origin with MARKETPLACE_CORS_ORIGINS=https://carvibes.dev.
// ============================================================

import { createReadStream } from "node:fs";
import { realpath, stat } from "node:fs/promises";
import { createServer } from "node:http";
import path from "node:path";
import { createMarketplaceHandler } from "./handler.mjs";
import { ADMIN_EMAILS, GOOGLE_CLIENT_ID, MEDIA_URL_PREFIX, paths } from "./config.mjs";

const PORT = Number(process.env.MARKETPLACE_PORT ?? process.env.PORT ?? 8787);
const HOST = process.env.MARKETPLACE_HOST ?? "0.0.0.0";

const handler = createMarketplaceHandler();

const server = createServer(async (req, res) => {
  const url = req.url ?? "/";
  if (url === "/" || url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true, service: "carvibes-marketplace-api" }));
    return;
  }
  // Uploaded listing photos, served by this same process (the static site
  // proxies the path to us). Query strings carry no meaning here.
  if (url.startsWith(MEDIA_PREFIX)) {
    try {
      await serveMediaFile(req, res, url.split("?")[0]);
    } catch {
      if (!res.headersSent) sendJson(res, 404, { error: "not_found" });
      else res.destroy();
    }
    return;
  }

  if (!url.startsWith("/api/marketplace")) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: "not_found" }));
    return;
  }
  // Last-resort guard: an unhandled rejection in a request listener takes the
  // whole API process down, so the handler is never allowed to escape.
  try {
    await handler(req, res);
  } catch (error) {
    console.error("[marketplace] unhandled handler error:", error);
    if (!res.headersSent) sendJson(res, Number(error?.status) || 500, { error: "server_error" });
    else res.destroy();
  }
});

// ------------------------------------------------------------
// Listing photos (read-only static files)
// ------------------------------------------------------------
// Only files inside MARKETPLACE_MEDIA_DIR are ever reachable, and only
// through the configured prefix. Every request is checked three times
// (segments, resolved path, real path) because this endpoint is the one
// place where a URL that comes from the internet turns into a filesystem
// path.
// ------------------------------------------------------------
const MEDIA_ROOT = path.resolve(paths.mediaDir);
const MEDIA_PREFIX = MEDIA_URL_PREFIX.endsWith("/") ? MEDIA_URL_PREFIX : `${MEDIA_URL_PREFIX}/`;

/** Extensions the API can produce. Anything else is not ours to serve. */
const MEDIA_TYPES = new Map([
  [".webp", "image/webp"],
  [".png", "image/png"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".avif", "image/avif"],
  [".gif", "image/gif"],
]);

// A photo URL is immutable: its file name is generated by the server, it
// is written once (staging → listing) and never rewritten, so it can be
// cached forever. The ETag still makes a stale edge cache revalidate.
const MEDIA_CACHE = "public, max-age=31536000, immutable";

let mediaRealRootPromise = null;
const mediaRealRoot = () =>
  (mediaRealRootPromise ??= realpath(MEDIA_ROOT).catch(() => MEDIA_ROOT));

function sendJson(res, status, body, extraHeaders = {}) {
  res.writeHead(status, { "content-type": "application/json", ...extraHeaders });
  res.end(JSON.stringify(body));
}

async function serveMediaFile(req, res, pathname) {
  if (req.method !== "GET" && req.method !== "HEAD") {
    return sendJson(res, 405, { error: "method_not_allowed" }, { allow: "GET, HEAD" });
  }

  // The URL is percent-decoded ONCE, then validated as a whole: decoding
  // before splitting is what makes encoded traversal (%2e%2e%2f, %2f, …)
  // land in the same checks as its plain form.
  let relative;
  try {
    relative = decodeURIComponent(pathname.slice(MEDIA_PREFIX.length));
  } catch {
    return sendJson(res, 404, { error: "not_found" }); // malformed encoding
  }

  // Layer 1 — shape: a plain relative path of ordinary segments only.
  const segments = relative.split("/");
  if (
    !relative ||
    relative.includes("\\") ||
    relative.includes("\0") ||
    segments.some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    return sendJson(res, 404, { error: "not_found" });
  }

  // Layer 2 — containment: the resolved path must sit under the media root.
  const target = path.resolve(MEDIA_ROOT, relative);
  if (!target.startsWith(MEDIA_ROOT + path.sep)) {
    return sendJson(res, 404, { error: "not_found" });
  }

  // Only known image types are served, which also removes any file the
  // media directory might hold besides photos.
  const type = MEDIA_TYPES.get(path.extname(target).toLowerCase());
  if (!type) return sendJson(res, 404, { error: "not_found" });

  // Layer 3 — real path: a symlink inside the volume must not escape it.
  let real;
  try {
    real = await realpath(target);
  } catch {
    return sendJson(res, 404, { error: "not_found" });
  }
  const realRoot = await mediaRealRoot();
  if (real !== realRoot && !real.startsWith(realRoot + path.sep)) {
    return sendJson(res, 404, { error: "not_found" });
  }

  let info;
  try {
    info = await stat(real);
  } catch {
    return sendJson(res, 404, { error: "not_found" });
  }
  if (!info.isFile()) return sendJson(res, 404, { error: "not_found" });

  const etag = `"${info.size.toString(16)}-${Math.floor(info.mtimeMs).toString(16)}"`;
  const headers = {
    "content-type": type,
    "content-length": String(info.size),
    "cache-control": MEDIA_CACHE,
    "last-modified": info.mtime.toUTCString(),
    etag,
    // Never let a browser re-interpret the bytes as something else.
    "x-content-type-options": "nosniff",
  };

  if (req.headers["if-none-match"] === etag) {
    res.writeHead(304, { etag, "cache-control": MEDIA_CACHE });
    res.end();
    return;
  }
  if (req.method === "HEAD") {
    res.writeHead(200, headers);
    res.end();
    return;
  }

  res.writeHead(200, headers);
  const stream = createReadStream(real);
  stream.on("error", () => res.destroy());
  stream.pipe(res);
}

server.listen(PORT, HOST, () => {
  console.log(`[marketplace] API listening on http://${HOST}:${PORT}/api/marketplace`);
  console.log(`[marketplace] storage: ${paths.dataDir}`);
  console.log(`[marketplace] media  : ${paths.mediaDir} (served read-only at ${MEDIA_URL_PREFIX}/)`);
  console.log(`[marketplace] admins : ${ADMIN_EMAILS.length ? ADMIN_EMAILS.map(mask).join(", ") : "NONE — set MARKETPLACE_ADMIN_EMAILS"}`);
  console.log(`[marketplace] google : ${GOOGLE_CLIENT_ID ? "configured" : "NOT configured"}`);
});

function mask(email) {
  const [user, domain] = email.split("@");
  return `${user.slice(0, 2)}***@${domain}`;
}

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    console.log(`\n[marketplace] ${signal} — shutting down.`);
    server.close(() => process.exit(0));
  });
}
