// ============================================================
// CARVIBES — prebuild: generate src/lib/counts.ts
//
// The Hero shows live database counts (cars / brands / stories /
// categories). Importing db.ts + stories.ts just for `.length` pins the
// ENTIRE car + story datasets (~200 KB) to the entry bundle — every route
// would download them before first paint, including pages that never show
// a car (privacy policy, 404, …).
//
// This script evaluates the real data once (same trick as the sitemap
// generator — never regex-scraped) and writes a tiny static module. The
// homepage's lazy sections still import the full data where it is really
// used, so the numbers above the fold can never drift from the lists
// below it.
// ============================================================
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src", "lib", "counts.ts");

async function main() {
  const dir = mkdtempSync(path.join(tmpdir(), "carvibes-counts-"));
  const dataEntry = path.join(dir, "data-entry.ts");
  const countsFile = path.join(dir, "counts.json");
  writeFileSync(
    dataEntry,
    [
      `import { cars, allBrands } from ${JSON.stringify(path.join(ROOT, "src/lib/db.ts"))};`,
      `import { stories } from ${JSON.stringify(path.join(ROOT, "src/lib/stories.ts"))};`,
      `import { categoryList } from ${JSON.stringify(path.join(ROOT, "src/lib/cars.ts"))};`,
      `import { writeFileSync } from "node:fs";`,
      `writeFileSync(${JSON.stringify(countsFile)}, JSON.stringify({`,
      `  cars: cars.length, brands: allBrands.length, stories: stories.length, categories: categoryList.length,`,
      `}));`,
    ].join("\n"),
    "utf8"
  );
  await build({
    entryPoints: [dataEntry],
    outfile: path.join(dir, "data.mjs"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node18",
    logLevel: "silent",
  });
  await import(pathToFileURL(path.join(dir, "data.mjs")).href);
  const { cars, brands, stories, categories } = JSON.parse(
    readFileSync(countsFile, "utf8")
  );
  rmSync(dir, { recursive: true, force: true });

  const ts = [
    `// GENERATED by scripts/generate-counts.mjs at prebuild — do not edit.`,
    `// Live database counts, frozen from the real data at build time so the`,
    `// hero can render them without shipping the car/story datasets to every`,
    `// route. \`npm run build\` regenerates this file; the prerendered HTML`,
    `// and these numbers are stamped from the same snapshot.`,
    `export const COUNTS = {`,
    `  cars: ${cars},`,
    `  brands: ${brands},`,
    `  stories: ${stories},`,
    `  categories: ${categories},`,
    `} as const;`,
    ``,
  ].join("\n");
  writeFileSync(OUT, ts, "utf8");
  console.log(
    `[counts] src/lib/counts.ts → ${cars} cars · ${brands} brands · ${stories} stories · ${categories} categories`
  );

  // ---------------------------------------------------------------
  // Quiz hub counts — same trick a second time. The /car-quiz hub
  // shows "N questions" and per-quiz max-reward figures; before this,
  // rendering those two numbers statically imported the ENTIRE
  // question bank (~150 KB) into the hub chunk, delaying the hub's
  // LCP text and adding ~120 ms of TBT on a Moto G4 class device.
  // The bank now rides the lazy player chunk only.
  // ---------------------------------------------------------------
  const quizDir = mkdtempSync(path.join(tmpdir(), "carvibes-quiz-counts-"));
  const quizEntry = path.join(quizDir, "quiz-entry.ts");
  const quizOutFile = path.join(quizDir, "quiz-counts.json");
  writeFileSync(
    quizEntry,
    [
      `import { QUESTIONS } from ${JSON.stringify(path.join(ROOT, "src/lib/quiz/data/index.ts"))};`,
      `import { QUIZZES } from ${JSON.stringify(path.join(ROOT, "src/lib/quiz/quizzes.ts"))};`,
      `import { computeMaxReward } from ${JSON.stringify(path.join(ROOT, "src/lib/quiz/bank.ts"))};`,
      `import { writeFileSync } from "node:fs";`,
      `writeFileSync(${JSON.stringify(quizOutFile)}, JSON.stringify({`,
      `  total: QUESTIONS.length,`,
      `  rewards: Object.fromEntries(QUIZZES.map((q) => [q.id, computeMaxReward(q)])),`,
      `}));`,
    ].join("\n"),
    "utf8"
  );
  await build({
    entryPoints: [quizEntry],
    outfile: path.join(quizDir, "quiz.mjs"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node18",
    logLevel: "silent",
  });
  await import(pathToFileURL(path.join(quizDir, "quiz.mjs")).href);
  const quiz = JSON.parse(readFileSync(quizOutFile, "utf8"));
  rmSync(quizDir, { recursive: true, force: true });

  const QUIZ_OUT = path.join(ROOT, "src", "lib", "quiz", "counts.ts");
  const quizTs = [
    `// GENERATED by scripts/generate-counts.mjs at prebuild — do not edit.`,
    `// Question-bank figures the /car-quiz hub renders WITHOUT importing the`,
    `// bank itself (total count + per-quiz max reward, computed from the real`,
    `// data by the same functions the player uses). \`npm run build\``,
    `// regenerates this file; smoke-quiz/validate-quiz re-check the numbers`,
    `// against the live bank, so a stale file fails the build pipeline.`,
    `export const TOTAL_QUESTIONS = ${quiz.total};`,
    ``,
    `export const MAX_REWARDS: Record<string, number> = {`,
    ...Object.entries(quiz.rewards).map(
      ([id, pts]) => `  ${JSON.stringify(id)}: ${pts},`
    ),
    `};`,
    ``,
  ].join("\n");
  writeFileSync(QUIZ_OUT, quizTs, "utf8");
  console.log(
    `[counts] src/lib/quiz/counts.ts → ${quiz.total} questions · ${Object.keys(quiz.rewards).length} max-reward figures`
  );
}

main().catch((e) => {
  console.error("[counts] FAILED:", e);
  process.exit(1);
});
